web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NOVE_ENV: development
db:
  image: mongo:latest
  ports:
   - "27017:27017"

